In [4]:
import torch as t
import numpy as np
import pandas as pd

In [5]:
file_path = 'data_mod.csv'
data = pd.read_csv(file_path)
print(data)

      price  bedrooms  bathrooms  sqft_living  sqft_lot  floors
0    313000         3       1.50         1340      7912     1.5
1   2384000         5       2.50         3650      9050     2.0
2    342000         3       2.00         1930     11947     1.0
3    420000         3       2.25         2000      8030     1.0
4    550000         4       2.50         1940     10500     1.0
..      ...       ...        ...          ...       ...     ...
94   524000         3       1.75         1560      5520     1.0
95   541125         5       2.75         2740      8426     1.0
96   670000         3       2.50         1680      2000     3.0
97   384900         5       2.50         3090     12750     1.0
98   406100         3       2.25         1410      1332     3.0

[99 rows x 6 columns]


In [6]:
features = data.drop(columns=['price']).values.astype('float32')
target = data['price'].values.astype('float32').reshape(-1, 1)


In [7]:
print(features.shape)
print(target.shape)

(99, 5)
(99, 1)


In [8]:
inputs = t.from_numpy(features)
targets = t.from_numpy(target)



In [9]:
print(inputs)
print(targets)

tensor([[3.0000e+00, 1.5000e+00, 1.3400e+03, 7.9120e+03, 1.5000e+00],
        [5.0000e+00, 2.5000e+00, 3.6500e+03, 9.0500e+03, 2.0000e+00],
        [3.0000e+00, 2.0000e+00, 1.9300e+03, 1.1947e+04, 1.0000e+00],
        [3.0000e+00, 2.2500e+00, 2.0000e+03, 8.0300e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 1.9400e+03, 1.0500e+04, 1.0000e+00],
        [2.0000e+00, 1.0000e+00, 8.8000e+02, 6.3800e+03, 1.0000e+00],
        [2.0000e+00, 2.0000e+00, 1.3500e+03, 2.5600e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 2.7100e+03, 3.5868e+04, 2.0000e+00],
        [3.0000e+00, 2.5000e+00, 2.4300e+03, 8.8426e+04, 1.0000e+00],
        [4.0000e+00, 2.0000e+00, 1.5200e+03, 6.2000e+03, 1.5000e+00],
        [3.0000e+00, 1.7500e+00, 1.7100e+03, 7.3200e+03, 1.0000e+00],
        [4.0000e+00, 2.5000e+00, 2.9200e+03, 4.0000e+03, 1.5000e+00],
        [3.0000e+00, 1.7500e+00, 2.3300e+03, 1.4892e+04, 1.0000e+00],
        [3.0000e+00, 1.0000e+00, 1.0900e+03, 6.4350e+03, 1.0000e+00],
        [5.0000e+00,

In [10]:
W = t.randn(1, 5, requires_grad=True)
b = t.randn(1, requires_grad=True)


In [11]:
print(W)

tensor([[-0.2719, -0.7023, -1.1503, -0.0344, -0.4630]], requires_grad=True)


In [12]:
print(b)

tensor([1.1072], requires_grad=True)


In [13]:
def model(x):
    out = x @ W.t() + b
    return out


In [14]:
def mse(y):
    diff = t.mean((targets - y) ** 2)
    return diff

In [15]:
learning_rate = 5e-5  # Use a smaller learning rate
iterations = 10000


In [16]:
for i in range(iterations):
    # Forward pass: Compute predicted y by passing inputs to the model
    pred = model(inputs)

In [17]:
print(pred)

tensor([[-1815.0676],
        [-4512.8770],
        [-2632.6875],
        [-2578.6165],
        [-2595.0286],
        [-1232.3685],
        [-1642.2794],
        [-4354.0200],
        [-5839.4956],
        [-1963.8412],
        [-2220.2522],
        [-3498.9109],
        [-3193.9541],
        [-1476.0945],
        [-3676.3987],
        [-1716.0006],
        [-2037.7042],
        [-3829.2144],
        [-1778.8514],
        [-1712.1586],
        [-2942.4648],
        [-1971.8416],
        [-2069.5461],
        [-3564.8123],
        [-2061.6506],
        [-2778.7922],
        [-2966.9453],
        [-2919.9651],
        [-5569.7637],
        [-3156.1179],
        [-2095.4600],
        [-3407.5894],
        [-2267.6423],
        [-3535.7734],
        [-5653.4487],
        [-4869.9233],
        [-1087.7045],
        [-2817.2651],
        [-2706.8660],
        [-2976.4866],
        [-2377.1035],
        [-2001.0317],
        [-1190.7722],
        [-2137.3267],
        [-1715.8706],
        [-

In [18]:
 # Compute and print loss
error = mse(pred)

In [19]:
print(error)

tensor(3.8412e+11, grad_fn=<MeanBackward0>)


In [20]:
error.backward()

In [21]:
print(error)

tensor(3.8412e+11, grad_fn=<MeanBackward0>)


In [22]:
  # Update weights and biases
with t.no_grad():
 W -= learning_rate * W.grad
 b -= learning_rate * b.grad

In [23]:
print(W)

tensor([[1.9548e+02, 1.2205e+02, 1.2724e+05, 7.8412e+05, 8.5091e+01]],
       requires_grad=True)


In [24]:
print(b)

tensor([56.6041], requires_grad=True)


In [25]:
  # Manually zero the gradients after updating weights
W.grad.zero_()
b.grad.zero_()

tensor([0.])

In [26]:
print(W)

tensor([[1.9548e+02, 1.2205e+02, 1.2724e+05, 7.8412e+05, 8.5091e+01]],
       requires_grad=True)


In [27]:
 if i % 1000 == 0:
  print(f"Iteration {i}, Error: {error.item()}")
  print(f"W: {W}, b: {b.item()}")

In [28]:
# Print final predictions and error
pred = model(inputs)
final_error = mse(pred)
print(f"Final Error: {final_error.item()}")
print(pred)


Final Error: 3.474550686045637e+20
tensor([[6.3745e+09],
        [7.5608e+09],
        [9.6135e+09],
        [6.5510e+09],
        [8.4802e+09],
        [5.1147e+09],
        [2.1791e+09],
        [2.8470e+10],
        [6.9646e+10],
        [5.0550e+09],
        [5.9574e+09],
        [3.5080e+09],
        [1.1974e+10],
        [5.1845e+09],
        [7.8038e+09],
        [7.7744e+09],
        [5.4534e+09],
        [6.0657e+09],
        [4.7677e+09],
        [8.2086e+09],
        [8.5795e+09],
        [7.0848e+09],
        [1.4553e+09],
        [9.9615e+09],
        [5.2063e+09],
        [8.7611e+09],
        [6.0173e+09],
        [9.1013e+09],
        [5.3301e+10],
        [4.0554e+09],
        [7.0204e+09],
        [2.9868e+09],
        [4.1522e+09],
        [6.9517e+09],
        [3.4088e+10],
        [2.6407e+10],
        [3.9048e+09],
        [1.5891e+10],
        [1.0521e+10],
        [5.4401e+09],
        [1.2916e+10],
        [6.9514e+09],
        [4.9493e+09],
        [2.4796e+09